{% set name = "nrel.routee.compass" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d325501fc1b39f5117eeb5005edd574cfb81690aaafaba3947c6fa1b64c2ca42

build:
  number: 0
  skip: true  # [py<39 or python_impl == 'pypy']
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cd rust
    - cargo-bundle-licenses --format yaml --output ../THIRDPARTY.yml
  # missing_dso_whitelist:
  #   - "$RPATH/libstdc++.so.6"   
  #   - "$RPATH/api-ms-win-core-path-l1-1-0.dll"    

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}                    # [unix]
    - {{ compiler('cxx') }}                    
    - libcxx
    - rust
    - cargo-bundle-licenses
  host:
    - pip
    - maturin
    - python
  run:
    - python
    - osmnx
    - toml

test:
  imports:
    - nrel.routee.compass
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://nrel.github.io/routee-compass/
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  summary: The RouteE-Compass energy-aware routing engine.
  description: |
    RouteE Compass is an energy-aware routing engine for the RouteE ecosystem of software tools. 
    It supports dynamic and extensible search objectives that allow customized blends of distance, 
    time, cost, and energy (via RouteE Powertrain) at query-time. The core engine is written in 
    Rust for improved runtimes, parallel query execution, and the ability to load nation-sized 
    road networks into memory.

extra:
  recipe-maintainers:
    - robfitzgerald
    - nreinicke
