{% set name = "nrel.routee.compass" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3558d3393084d26c050bf53ba7f745a25d050cac62dac1c8e5115ca8e9b9b12a

build:
  number: 0
  skip: true  # [py<39 or python_impl == 'pypy']
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cd rust
    - cargo-bundle-licenses --format yaml --output ../THIRDPARTY.yml
  missing_dso_whitelist:
    - '**/api-ms-win-core-path-l1-1-0.dll'  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - maturin
  host:
    - pip
    - maturin
    - python
  run:
    - python
    - osmnx
    - toml

test:
  imports:
    - nrel.routee.compass
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://nrel.github.io/routee-compass/
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  summary: The RouteE-Compass energy-aware routing engine.
  description: |
    RouteE Compass is an energy-aware routing engine for the RouteE ecosystem of software tools. 
    It supports dynamic and extensible search objectives that allow customized blends of distance, 
    time, cost, and energy (via RouteE Powertrain) at query-time. The core engine is written in 
    Rust for improved runtimes, parallel query execution, and the ability to load nation-sized 
    road networks into memory.

extra:
  recipe-maintainers:
    - robfitzgerald
    - nreinicke
